### PR TITLE
fix: guard against null history.state in createHandlePopState

### LINKED ISSUE #10: __next_navigation_guard_token evaluation crashes
Sometimes I get this error: https://yung.sentry.io/share/issue/62bb003ffa7c48559c576b138a9a7cbc/ (actual trace of a crash)

The error is: ```null is not an object (evaluating 't.__next_navigation_guard_token')```

It happens here: [
](https://github.com/LayerXcom/next-navigation-guard/blob/bfa61da4a3c132dea4e577f0bbddf4c57b53f9c5/src/hooks/useInterceptPopState.ts#L63)

### PR DESCRIPTION
**Pull request by sethcarlton**
This PR prevents a runtime error in `useInterceptPopState` when navigating to the same page with a different hash (or anytime `history.state` may be null)

Fixes: #10

### CODE REVIEW

File: src/hooks/useInterceptPopState.ts [hunk 1]
```diff
@@ -59,7 +59,8 @@ function createHandlePopState(
 ) {
   let dispatchedState: unknown;
 
-  return (nextState: any): boolean => {
+  return (rawNextState: any): boolean => {
+    const nextState = rawNextState ?? {};
```
Comment (grod) [inline src/hooks/useInterceptPopState.ts]: Can't you do this?

```suggestion
  return (nextState: any = {}): boolean => {
```

**Comment by ypresto** [comment]
thanks :tada:
